goog.provide('kuhumcst.recap.state');
cljs.spec.alpha.def_impl(new cljs.core.Keyword("kuhumcst.recap.state","i","kuhumcst.recap.state/i",-1997646213),new cljs.core.Symbol("cljs.core","int?","cljs.core/int?",50730120,null),cljs.core.int_QMARK_);
cljs.spec.alpha.def_impl(new cljs.core.Keyword("kuhumcst.recap.state","coll","kuhumcst.recap.state/coll",-1957757527),new cljs.core.Symbol("cljs.core","sequential?","cljs.core/sequential?",1777854658,null),cljs.core.sequential_QMARK_);
cljs.spec.alpha.def_impl(new cljs.core.Keyword("kuhumcst.recap.state","kv","kuhumcst.recap.state/kv",-611845790),cljs.core.list(new cljs.core.Symbol("cljs.spec.alpha","tuple","cljs.spec.alpha/tuple",-415901908,null),new cljs.core.Symbol("cljs.core","any?","cljs.core/any?",-2068111842,null),new cljs.core.Symbol("cljs.core","any?","cljs.core/any?",-2068111842,null)),cljs.spec.alpha.tuple_impl.cljs$core$IFn$_invoke$arity$2(new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol("cljs.core","any?","cljs.core/any?",-2068111842,null),new cljs.core.Symbol("cljs.core","any?","cljs.core/any?",-2068111842,null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.any_QMARK_,cljs.core.any_QMARK_], null)));
cljs.spec.alpha.def_impl(new cljs.core.Keyword("kuhumcst.recap.state","kvs","kuhumcst.recap.state/kvs",511167398),cljs.core.list(new cljs.core.Symbol("cljs.spec.alpha","coll-of","cljs.spec.alpha/coll-of",1019430407,null),new cljs.core.Keyword("kuhumcst.recap.state","kv","kuhumcst.recap.state/kv",-611845790)),cljs.spec.alpha.every_impl.cljs$core$IFn$_invoke$arity$4(new cljs.core.Keyword("kuhumcst.recap.state","kv","kuhumcst.recap.state/kv",-611845790),new cljs.core.Keyword("kuhumcst.recap.state","kv","kuhumcst.recap.state/kv",-611845790),new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword("cljs.spec.alpha","kind-form","cljs.spec.alpha/kind-form",-1047104697),null,new cljs.core.Keyword("cljs.spec.alpha","cpred","cljs.spec.alpha/cpred",-693471218),(function (G__52382){
return cljs.core.coll_QMARK_(G__52382);
}),new cljs.core.Keyword("cljs.spec.alpha","conform-all","cljs.spec.alpha/conform-all",45201917),true,new cljs.core.Keyword("cljs.spec.alpha","describe","cljs.spec.alpha/describe",1883026911),cljs.core.list(new cljs.core.Symbol("cljs.spec.alpha","coll-of","cljs.spec.alpha/coll-of",1019430407,null),new cljs.core.Keyword("kuhumcst.recap.state","kv","kuhumcst.recap.state/kv",-611845790))], null),null));
cljs.spec.alpha.def_impl(new cljs.core.Keyword("kuhumcst.recap.state","kvs+i","kuhumcst.recap.state/kvs+i",13151152),cljs.core.list(new cljs.core.Symbol("cljs.spec.alpha","keys","cljs.spec.alpha/keys",1109346032,null),new cljs.core.Keyword(null,"req-un","req-un",1074571008),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("kuhumcst.recap.state","kvs","kuhumcst.recap.state/kvs",511167398)], null),new cljs.core.Keyword(null,"opt-un","opt-un",883442496),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("kuhumcst.recap.state","i","kuhumcst.recap.state/i",-1997646213)], null)),cljs.spec.alpha.map_spec_impl(cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"req-un","req-un",1074571008),new cljs.core.Keyword(null,"opt-un","opt-un",883442496),new cljs.core.Keyword(null,"gfn","gfn",791517474),new cljs.core.Keyword(null,"pred-exprs","pred-exprs",1792271395),new cljs.core.Keyword(null,"keys-pred","keys-pred",858984739),new cljs.core.Keyword(null,"opt-keys","opt-keys",1262688261),new cljs.core.Keyword(null,"req-specs","req-specs",553962313),new cljs.core.Keyword(null,"req","req",-326448303),new cljs.core.Keyword(null,"req-keys","req-keys",514319221),new cljs.core.Keyword(null,"opt-specs","opt-specs",-384905450),new cljs.core.Keyword(null,"pred-forms","pred-forms",172611832),new cljs.core.Keyword(null,"opt","opt",-794706369)],[new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("kuhumcst.recap.state","kvs","kuhumcst.recap.state/kvs",511167398)], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("kuhumcst.recap.state","i","kuhumcst.recap.state/i",-1997646213)], null),null,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(function (G__52385){
return cljs.core.map_QMARK_(G__52385);
}),(function (G__52385){
return cljs.core.contains_QMARK_(G__52385,new cljs.core.Keyword(null,"kvs","kvs",958455492));
})], null),(function (G__52385){
return ((cljs.core.map_QMARK_(G__52385)) && (cljs.core.contains_QMARK_(G__52385,new cljs.core.Keyword(null,"kvs","kvs",958455492))));
}),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"i","i",-1386841315)], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("kuhumcst.recap.state","kvs","kuhumcst.recap.state/kvs",511167398)], null),null,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"kvs","kvs",958455492)], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("kuhumcst.recap.state","i","kuhumcst.recap.state/i",-1997646213)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.list(new cljs.core.Symbol("cljs.core","fn","cljs.core/fn",-1065745098,null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"%","%",-950237169,null)], null),cljs.core.list(new cljs.core.Symbol("cljs.core","map?","cljs.core/map?",-1390345523,null),new cljs.core.Symbol(null,"%","%",-950237169,null))),cljs.core.list(new cljs.core.Symbol("cljs.core","fn","cljs.core/fn",-1065745098,null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"%","%",-950237169,null)], null),cljs.core.list(new cljs.core.Symbol("cljs.core","contains?","cljs.core/contains?",-976526835,null),new cljs.core.Symbol(null,"%","%",-950237169,null),new cljs.core.Keyword(null,"kvs","kvs",958455492)))], null),null])));
cljs.spec.alpha.def_impl(new cljs.core.Keyword("kuhumcst.recap.state","coll+i","kuhumcst.recap.state/coll+i",-1456102351),cljs.core.list(new cljs.core.Symbol("cljs.spec.alpha","keys","cljs.spec.alpha/keys",1109346032,null),new cljs.core.Keyword(null,"req-un","req-un",1074571008),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("kuhumcst.recap.state","coll","kuhumcst.recap.state/coll",-1957757527),new cljs.core.Keyword("kuhumcst.recap.state","i","kuhumcst.recap.state/i",-1997646213)], null)),cljs.spec.alpha.map_spec_impl(cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"req-un","req-un",1074571008),new cljs.core.Keyword(null,"opt-un","opt-un",883442496),new cljs.core.Keyword(null,"gfn","gfn",791517474),new cljs.core.Keyword(null,"pred-exprs","pred-exprs",1792271395),new cljs.core.Keyword(null,"keys-pred","keys-pred",858984739),new cljs.core.Keyword(null,"opt-keys","opt-keys",1262688261),new cljs.core.Keyword(null,"req-specs","req-specs",553962313),new cljs.core.Keyword(null,"req","req",-326448303),new cljs.core.Keyword(null,"req-keys","req-keys",514319221),new cljs.core.Keyword(null,"opt-specs","opt-specs",-384905450),new cljs.core.Keyword(null,"pred-forms","pred-forms",172611832),new cljs.core.Keyword(null,"opt","opt",-794706369)],[new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("kuhumcst.recap.state","coll","kuhumcst.recap.state/coll",-1957757527),new cljs.core.Keyword("kuhumcst.recap.state","i","kuhumcst.recap.state/i",-1997646213)], null),null,null,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(function (G__52394){
return cljs.core.map_QMARK_(G__52394);
}),(function (G__52394){
return cljs.core.contains_QMARK_(G__52394,new cljs.core.Keyword(null,"coll","coll",1647737163));
}),(function (G__52394){
return cljs.core.contains_QMARK_(G__52394,new cljs.core.Keyword(null,"i","i",-1386841315));
})], null),(function (G__52394){
return ((cljs.core.map_QMARK_(G__52394)) && (cljs.core.contains_QMARK_(G__52394,new cljs.core.Keyword(null,"coll","coll",1647737163))) && (cljs.core.contains_QMARK_(G__52394,new cljs.core.Keyword(null,"i","i",-1386841315))));
}),cljs.core.PersistentVector.EMPTY,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("kuhumcst.recap.state","coll","kuhumcst.recap.state/coll",-1957757527),new cljs.core.Keyword("kuhumcst.recap.state","i","kuhumcst.recap.state/i",-1997646213)], null),null,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"coll","coll",1647737163),new cljs.core.Keyword(null,"i","i",-1386841315)], null),cljs.core.PersistentVector.EMPTY,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.list(new cljs.core.Symbol("cljs.core","fn","cljs.core/fn",-1065745098,null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"%","%",-950237169,null)], null),cljs.core.list(new cljs.core.Symbol("cljs.core","map?","cljs.core/map?",-1390345523,null),new cljs.core.Symbol(null,"%","%",-950237169,null))),cljs.core.list(new cljs.core.Symbol("cljs.core","fn","cljs.core/fn",-1065745098,null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"%","%",-950237169,null)], null),cljs.core.list(new cljs.core.Symbol("cljs.core","contains?","cljs.core/contains?",-976526835,null),new cljs.core.Symbol(null,"%","%",-950237169,null),new cljs.core.Keyword(null,"coll","coll",1647737163))),cljs.core.list(new cljs.core.Symbol("cljs.core","fn","cljs.core/fn",-1065745098,null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"%","%",-950237169,null)], null),cljs.core.list(new cljs.core.Symbol("cljs.core","contains?","cljs.core/contains?",-976526835,null),new cljs.core.Symbol(null,"%","%",-950237169,null),new cljs.core.Keyword(null,"i","i",-1386841315)))], null),null])));
/**
 * Assert that the current value of `state` conforms to the given `spec`.
 */
kuhumcst.recap.state.assert_valid = (function kuhumcst$recap$state$assert_valid(state,spec){
if(cljs.spec.alpha.valid_QMARK_.cljs$core$IFn$_invoke$arity$2(spec,cljs.core.deref(state))){
return null;
} else {
throw (new Error(["Assert failed: ",cljs.spec.alpha.explain_str(spec,cljs.core.deref(state)),"\n","(s/valid? spec (clojure.core/deref state))"].join('')));
}
});
/**
 * Make sure that `state` provided as a plain map can also be dereferenced.
 */
kuhumcst.recap.state.normalize = (function kuhumcst$recap$state$normalize(state){
if(cljs.core.map_QMARK_(state)){
return reagent.core.atom.cljs$core$IFn$_invoke$arity$1(state);
} else {
return state;
}
});
/**
 * Normalize and validate a piece of `state` according to `spec`.
 */
kuhumcst.recap.state.prepare = (function kuhumcst$recap$state$prepare(spec,state){
var G__52407 = kuhumcst.recap.state.normalize(state);
kuhumcst.recap.state.assert_valid(G__52407,spec);

return G__52407;
});

//# sourceMappingURL=kuhumcst.recap.state.js.map
